### ISSUE TITLE
Konfetti interactions

### ISSUE THREAD

**Issue by piezzo** [konfetti-app/konfetti-app#17]
- voting animations /design
- explain what konfetti can do (on first receipt)
- konfetti distribution on finished idea
- konfetti for event-visiting (geo-location awareness (like in dogerain))

**Comment by rootzoll** [comment]
Done:
 - voting animations /design
- konfetti distribution on finished idea

ToDo later on:
-  explain what konfetti can do (on first receipt)

**Comment by rootzoll** [comment]
call it a close
