### ISSUE TITLE
IntroScreen UI Fixes

### ISSUE THREAD

**Issue by rootzoll** [konfetti-app/konfetti-app#8]
- prevent side menu from "slide from left top open"
- vertical center slides on bigger screen and add more padding on ion-content
- enter code button, give more more active color on last slide or animate

**Comment by piezzo** [comment]
Additional findings from iPhoneX, iOS 11.2.2:
- app does not fill view vertically (top status bar not themed)
- top status bar is invisible (white on white) - probably related to previous point

![img_0077](https://user-images.githubusercontent.com/7838487/34878890-a395f972-f7ab-11e7-8e11-488aa275b91b.jpg)
![img_0076](https://user-images.githubusercontent.com/7838487/34878891-a3b7abe4-f7ab-11e7-8ece-ce8a51181da5.jpg)
